[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino

; Source files to include
src_dir = src

; Libraries to include
lib_deps = 
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BME280 Library
    milesburton/DallasTemperature
    paea/OneWire
    SparkFun/SparkFun HTU21D Humidity and Temperature Sensor
    ; Add any other required libraries here

; Build flags
build_flags = 
    -D ARDUINO_ARCH_AVR
    -D ARDUINO_AVR_NANO
    -D F_CPU=16000000L

; Serial monitor settings
monitor_speed = 9600